# Generated by Django 2.0.2 on 2018-03-04 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatos_groups', models.CharField(choices=[('AM', 'Amigos'), ('FA', 'Família'), ('TR', 'Trabalho')], default='AM', max_length=2)),
                ('name_contact', models.CharField(blank=True, default='', help_text='Nome Completo', max_length=32)),
                ('phone_contact', models.CharField(blank=True, default='', help_text='Telefone', max_length=32)),
                ('email_contact', models.EmailField(blank=True, default='', help_text='Endereço de E-mail', max_length=32)),
                ('address_contact', models.CharField(blank=True, default='', help_text='Endereço', max_length=150)),
                ('org_contact', models.CharField(blank=True, default='', help_text='Organização', max_length=150)),
                ('text_contact', models.TextField(blank=True, default='', help_text='Observação', max_length=255)),
                ('date_contact', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
